import openai
from key import key

openai.api_key = key

prompt1 = "Generative Pre-trained Transformer 3 (GPT-3) is an autoregressive language model that uses deep learning to produce human-like text. It is the third-generation language prediction model in the GPT-n series (and the successor to GPT-2) created by OpenAI, a San Francisco-based artificial intelligence research laboratory. GPT-3's full version has a capacity of 175 billion machine learning parameters. GPT3, which was introduced in May 2020, and was in beta testing as of July 2020, is part of a trend in natural language processing (NLP) systems of pre-trained language representations. The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks. Thirty-one OpenAI researchers and engineers presented the original May 28, 2020 paper introducing GPT-3. In their paper, they warned of GPT-3's potential dangers and called for research to mitigate risk."
prompt2 = "In the First World War, Devonport was the headquarters of Western Approaches Command until 1941 and Sunderland flying boats were operated by the Royal Australian Air Force. It was an important embarkation point for US troops for D-Day. The city was heavily bombed by the Luftwaffe, in a series of 59 raids known as the Plymouth Blitz. Although the dockyards were the principal targets, much of the city centre and over 3,700 houses were completely destroyed and more than 1,000 civilians lost their lives. This was largely due to Plymouth's status as a major port Charles Church was hit by incendiary bombs and partially destroyed in 1941 during the Blitz, but has not been demolished, as it is now an official permanent monument to the bombing of Plymouth during World War II."

response = openai.Completion.create(
    model="curie:ft-hdm-university-stuttgart-2022-01-19-12-00-30",
    prompt= prompt1,
    max_tokens=50,
    temperature = 0.6)
print(response.choices[0].text)

