import openai
from key import key
import xml.etree.cElementTree as ET
import xml.dom.minidom

openai.api_key = key

# insert ur context here
prompt = "Generative Pre-trained Transformer 3 (GPT-3) is an autoregressive language model that uses deep learning to produce human-like text. It is the third-generation language prediction model in the GPT-n series (and the successor to GPT-2) created by OpenAI, a San Francisco-based artificial intelligence research laboratory. GPT-3's full version has a capacity of 175 billion machine learning parameters. GPT3, which was introduced in May 2020, and was in beta testing as of July 2020, is part of a trend in natural language processing (NLP) systems of pre-trained language representations. The quality of the text generated by GPT-3 is so high that it can be difficult to determine whether or not it was written by a human, which has both benefits and risks. Thirty-one OpenAI researchers and engineers presented the original May 28, 2020 paper introducing GPT-3. In their paper, they warned of GPT-3's potential dangers and called for research to mitigate risk."

response = openai.Completion.create(
    model="curie:ft-hdm-university-stuttgart-2022-01-19-12-00-30",
    prompt= prompt,
    max_tokens=50,
    temperature = 0.6)

print(response.choices[0].text)

# create xml in a format moodle can work with to instantly create a quiz with our questions
m_encoding = 'UTF-8'

x= response.choices[0].text

root = ET.Element("quiz")
doc = ET.SubElement(root, "question")
ET.SubElement(doc, "text").text = x

dom = xml.dom.minidom.parseString(ET.tostring(root))
xml_string = dom.toprettyxml()
part1, part2 = xml_string.split('?>')

with open("FILE.xml", 'w') as xfile:
    xfile.write(part1 + 'encoding=\"{}\"?>\n'.format(m_encoding) + part2)
    xfile.close()